name: CI

on: [push]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  linux_build:

    name: Linux build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet build --configuration Release

  publish:

    name: Publish nuget package
    needs: linux_build
    runs-on: ubuntu-20.04

    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Knet.Kudu.Binary/Knet.Kudu.Binary.csproj
        NUGET_KEY: ${{secrets.KUDU_NUGET_API_KEY}}